---
- hosts: all
  gather_facts: false
  connection: local
  tasks: 
    - name: "Vérifier l'existance du peer-groupe"
      include_role:
        name: show_ip_bgp_peer-group

    - name: "Configuration sur les routers ASPI-BBH"
      include_role:
        name: config_bgp_peer_ASPI_BBH
      when: "'ASPI-BBH' in inventory_hostname"

    - name: "Configuration sur les routers ASPI-BBS"
      include_role:
        name: config_bgp_peer_ASPI_BBS
      when: "'ASPI-BBS' in inventory_hostname"

- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Creation du template Python Script
      template:
        src: ./roles/firewall_objet_creation/templates/script_python.j2
        dest: ./roles/firewall_objet_creation/files/fortiApi.py

    - name: execute install script sur les Firewalls
      include_role:
        name: firewall_objet_creation      
 
