---
# tasks file for deploiement_configuration

- name: "Configuration de la Crypto key de l'IP Wan 1"
  ios_config:
    lines:
      - crypto isakmp key inifposmeicl address {{ ip_wan1 }}

- name: "Configuration de la Crypto key de l'IP Wan 2"
  ios_config:
    lines:
      - crypto isakmp key inifposmeicl address {{ ip_wan2 }}
  when: ip_wan2 is defined

- name: "Configuration de la route pour ASPI-BBS1 de la WAN 1"
  ios_config:
    lines:
      - ip route {{ ip_wan1 }} 255.255.255.255 46.218.156.161
      - ip route {{ ip_peer_bgp1 }} 255.255.255.255 98.122.{{ uucp }}.61
  when: "'ASPI-BBS1' in inventory_hostname"

- name: "Configuration de la route pour ASPI-BBS1 de la WAN 2"
  ios_config:
    lines:
      - ip route {{ ip_wan2 }} 255.255.255.255 46.218.156.161
      - ip route {{ ip_peer_bgp2 }} 255.255.255.255 98.122.{{ uucp }}.159
  when: 
    - ip_wan2 is defined 
    - "'ASPI-BBS1' in inventory_hostname"

- name: "Configuration de la route pour ASPI-BBS2 de la WAN 1"
  ios_config:
    lines:
      - ip route {{ ip_wan1 }} 255.255.255.255 94.198.202.148
      - ip route {{ ip_peer_bgp1 }} 255.255.255.255 98.122.{{ uucp }}.59
  when: "'ASPI-BBS2' in inventory_hostname"

- name: "Configuration de la route pour ASPI-BBS2 de la WAN 2"
  ios_config:
    lines:
      - ip route {{ ip_wan2 }} 255.255.255.255 94.198.202.148
      - ip route {{ ip_peer_bgp2 }} 255.255.255.255 98.122.{{ uucp }}.161
  when:
    - ip_wan2 is defined
    - "'ASPI-BBS2' in inventory_hostname"

- name: "Configuration de l'ACL securité de l'IP WAN 1"
  ios_config:
    lines: 
      - permit ip host {{ ip_wan1 }} any
    parents: ip access-list extended securite

- name: "Configuration de l'ACL securité de l'IP WAN 2"
  ios_config:
    lines:
      - permit ip host {{ ip_wan2 }} any
    parents: ip access-list extended securite
  when: ip_wan2 is defined

- name: "Configuration BGP sur le router si IPWAN2 est utilisé"
  ios_config:
    lines:
      - neighbor {{ ip_peer_bgp1 }} peer-group {{ peer_name1 }}
      - neighbor {{ ip_peer_bgp2 }} peer-group {{ peer_name2 }}
    parents: router bgp 64620
  when:
    - ip_wan2 is defined
    - "'ASPI-BBS' in inventory_hostname"
  notify: save

- name: "Configuration BGP sur le router"
  ios_config:
    lines:
      - neighbor {{ ip_peer_bgp1 }} peer-group {{ peer_name1 }}
    parents: router bgp 64620
  when:
    - ip_wan2 is not defined
    - "'ASPI-BBS' in inventory_hostname"
  notify: save
